# Generated by Django 4.1.3 on 2022-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateField()),
                ('hora_comentario', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
                ('lectura', models.BooleanField(default=True)),
                ('actualizar', models.BooleanField(default=True)),
                ('borrar', models.BooleanField(default=True)),
                ('crear', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['nombre_rol'],
            },
        ),
    ]
