# Generated by Django 3.1.12 on 2022-11-28 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221127_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rol'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=80)),
                ('contrasenia', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=30)),
                ('id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rol')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionario',
                'ordering': ['cargo'],
            },
        ),
    ]
