# Generated by Django 3.1.12 on 2022-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateField()),
                ('hora_comentario', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
                'ordering': ['estado'],
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
