# Generated by Django 3.1.12 on 2022-11-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221128_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentario',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['estado'], 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='Comentario',
        ),
    ]
