# Generated by Django 3.1.12 on 2022-11-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221128_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rol'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rol'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rol'),
        ),
    ]
