# Generated by Django 3.1.12 on 2022-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221129_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiar',
            options={'ordering': ['id'], 'verbose_name_plural': 'Familiares'},
        ),
        migrations.AlterField(
            model_name='rol',
            name='actualizar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='borrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='crear',
            field=models.BooleanField(default=False),
        ),
    ]
