# Generated by Django 3.1.12 on 2022-11-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='paciente_id',
        ),
    ]
