# Generated by Django 3.1.12 on 2022-11-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_familiar_paciente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='user',
        ),
    ]
