# Generated by Django 3.1.12 on 2022-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221129_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hora_comentario',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
