# Generated by Django 3.1.12 on 2022-12-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
