# Generated by Django 3.1.12 on 2022-11-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20221127_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
